import 'package:myapp/core/services/data_service.dart';
import 'package:myapp/core/models/schedule_model.dart';

/// Сервис для создания примерного расписания
class ScheduleSeedService {
  /// Создает примерное расписание для пользователя
  static Future<void> createSampleSchedule(String userId) async {
    final schedule = [
      // Понедельник
      ScheduleModel(
        id: '${DateTime.now().millisecondsSinceEpoch}_1',
        userId: userId,
        subject: 'Русский язык',
        dayOfWeek: 'Понедельник',
        lessonNumber: 1,
        startTime: '09:00',
        endTime: '09:45',
        classroom: '101',
        teacher: 'Иванова И.И.',
      ),
      ScheduleModel(
        id: '${DateTime.now().millisecondsSinceEpoch}_2',
        userId: userId,
        subject: 'Русский язык',
        dayOfWeek: 'Понедельник',
        lessonNumber: 2,
        startTime: '09:55',
        endTime: '10:40',
        classroom: '101',
        teacher: 'Иванова И.И.',
      ),
      ScheduleModel(
        id: '${DateTime.now().millisecondsSinceEpoch}_3',
        userId: userId,
        subject: 'Литература',
        dayOfWeek: 'Понедельник',
        lessonNumber: 3,
        startTime: '11:00',
        endTime: '11:45',
        classroom: '102',
        teacher: 'Петрова П.П.',
      ),
      ScheduleModel(
        id: '${DateTime.now().millisecondsSinceEpoch}_4',
        userId: userId,
        subject: 'Литература',
        dayOfWeek: 'Понедельник',
        lessonNumber: 4,
        startTime: '11:55',
        endTime: '12:40',
        classroom: '102',
        teacher: 'Петрова П.П.',
      ),
      ScheduleModel(
        id: '${DateTime.now().millisecondsSinceEpoch}_5',
        userId: userId,
        subject: 'Математика',
        dayOfWeek: 'Понедельник',
        lessonNumber: 5,
        startTime: '12:50',
        endTime: '13:35',
        classroom: '201',
        teacher: 'Сидорова С.С.',
      ),
      ScheduleModel(
        id: '${DateTime.now().millisecondsSinceEpoch}_6',
        userId: userId,
        subject: 'Математика',
        dayOfWeek: 'Понедельник',
        lessonNumber: 6,
        startTime: '13:45',
        endTime: '14:30',
        classroom: '201',
        teacher: 'Сидорова С.С.',
      ),
      // Вторник
      ScheduleModel(
        id: '${DateTime.now().millisecondsSinceEpoch}_7',
        userId: userId,
        subject: 'Алгебра',
        dayOfWeek: 'Вторник',
        lessonNumber: 1,
        startTime: '09:00',
        endTime: '09:45',
        classroom: '201',
        teacher: 'Сидорова С.С.',
      ),
      ScheduleModel(
        id: '${DateTime.now().millisecondsSinceEpoch}_8',
        userId: userId,
        subject: 'Геометрия',
        dayOfWeek: 'Вторник',
        lessonNumber: 2,
        startTime: '09:55',
        endTime: '10:40',
        classroom: '201',
        teacher: 'Сидорова С.С.',
      ),
      ScheduleModel(
        id: '${DateTime.now().millisecondsSinceEpoch}_9',
        userId: userId,
        subject: 'Физика',
        dayOfWeek: 'Вторник',
        lessonNumber: 3,
        startTime: '11:00',
        endTime: '11:45',
        classroom: '301',
        teacher: 'Козлова К.К.',
      ),
      ScheduleModel(
        id: '${DateTime.now().millisecondsSinceEpoch}_10',
        userId: userId,
        subject: 'Химия',
        dayOfWeek: 'Вторник',
        lessonNumber: 4,
        startTime: '11:55',
        endTime: '12:40',
        classroom: '302',
        teacher: 'Морозова М.М.',
      ),
      // Среда
      ScheduleModel(
        id: '${DateTime.now().millisecondsSinceEpoch}_11',
        userId: userId,
        subject: 'История',
        dayOfWeek: 'Среда',
        lessonNumber: 1,
        startTime: '09:00',
        endTime: '09:45',
        classroom: '103',
        teacher: 'Николаева Н.Н.',
      ),
      ScheduleModel(
        id: '${DateTime.now().millisecondsSinceEpoch}_12',
        userId: userId,
        subject: 'Обществознание',
        dayOfWeek: 'Среда',
        lessonNumber: 2,
        startTime: '09:55',
        endTime: '10:40',
        classroom: '103',
        teacher: 'Николаева Н.Н.',
      ),
      ScheduleModel(
        id: '${DateTime.now().millisecondsSinceEpoch}_13',
        userId: userId,
        subject: 'Биология',
        dayOfWeek: 'Среда',
        lessonNumber: 3,
        startTime: '11:00',
        endTime: '11:45',
        classroom: '303',
        teacher: 'Волкова В.В.',
      ),
      ScheduleModel(
        id: '${DateTime.now().millisecondsSinceEpoch}_14',
        userId: userId,
        subject: 'География',
        dayOfWeek: 'Среда',
        lessonNumber: 4,
        startTime: '11:55',
        endTime: '12:40',
        classroom: '104',
        teacher: 'Орлова О.О.',
      ),
      // Четверг
      ScheduleModel(
        id: '${DateTime.now().millisecondsSinceEpoch}_15',
        userId: userId,
        subject: 'Английский язык',
        dayOfWeek: 'Четверг',
        lessonNumber: 1,
        startTime: '09:00',
        endTime: '09:45',
        classroom: '105',
        teacher: 'Смирнова С.С.',
      ),
      ScheduleModel(
        id: '${DateTime.now().millisecondsSinceEpoch}_16',
        userId: userId,
        subject: 'Английский язык',
        dayOfWeek: 'Четверг',
        lessonNumber: 2,
        startTime: '09:55',
        endTime: '10:40',
        classroom: '105',
        teacher: 'Смирнова С.С.',
      ),
      ScheduleModel(
        id: '${DateTime.now().millisecondsSinceEpoch}_17',
        userId: userId,
        subject: 'Информатика',
        dayOfWeek: 'Четверг',
        lessonNumber: 3,
        startTime: '11:00',
        endTime: '11:45',
        classroom: '401',
        teacher: 'Федорова Ф.Ф.',
      ),
      ScheduleModel(
        id: '${DateTime.now().millisecondsSinceEpoch}_18',
        userId: userId,
        subject: 'Физкультура',
        dayOfWeek: 'Четверг',
        lessonNumber: 4,
        startTime: '11:55',
        endTime: '12:40',
        classroom: 'Спортзал',
        teacher: 'Алексеев А.А.',
      ),
      // Пятница
      ScheduleModel(
        id: '${DateTime.now().millisecondsSinceEpoch}_19',
        userId: userId,
        subject: 'Русский язык',
        dayOfWeek: 'Пятница',
        lessonNumber: 1,
        startTime: '09:00',
        endTime: '09:45',
        classroom: '101',
        teacher: 'Иванова И.И.',
      ),
      ScheduleModel(
        id: '${DateTime.now().millisecondsSinceEpoch}_20',
        userId: userId,
        subject: 'Математика',
        dayOfWeek: 'Пятница',
        lessonNumber: 2,
        startTime: '09:55',
        endTime: '10:40',
        classroom: '201',
        teacher: 'Сидорова С.С.',
      ),
      ScheduleModel(
        id: '${DateTime.now().millisecondsSinceEpoch}_21',
        userId: userId,
        subject: 'ИЗО',
        dayOfWeek: 'Пятница',
        lessonNumber: 3,
        startTime: '11:00',
        endTime: '11:45',
        classroom: '106',
        teacher: 'Романова Р.Р.',
      ),
      ScheduleModel(
        id: '${DateTime.now().millisecondsSinceEpoch}_22',
        userId: userId,
        subject: 'Музыка',
        dayOfWeek: 'Пятница',
        lessonNumber: 4,
        startTime: '11:55',
        endTime: '12:40',
        classroom: '107',
        teacher: 'Лебедева Л.Л.',
      ),
    ];

    for (var lesson in schedule) {
      await DataService.createSchedule(lesson);
    }
  }
}
